### ISSUE TITLE
[Bug] Servly.Persistence.Redis is not on NuGet

### ISSUE THREAD

**Issue by CS-DanielW** [DrBarnabus/Servly#10]
# 🐞 Bug Report

### Affected Package(s)
Servly.Persistence.Redis

### Is this a regression?
No

### Description
The package is not pushed to NuGet rendering the idempotency package unusable.

## 🔬 Minimal Reproduction Steps
Try to install any package dependent on Servly.Persistence.Redis

## 🔥 Exception or Error Message

<pre><code>N/A</code></pre>

### Servly Version

<pre><code>v0.1.0</code></pre>

### .NET  Version:

.NET 6

**Comment by DrBarnabus** [comment]
This has been resolved, and will be on NuGet with the next tagged release.
